export const PRODUCT_NAME_MIN_LENGTH = 5;
export const PRODUCT_NAME_MAX_LENGTH = 60;

export const GET_ALL_ADMIN_PRODUCTS_MAX_LIMIT = 100;
export const GET_ALL_ADMIN_PRODUCTS_DEFAULT_LIMIT = 30;
export const GET_ALL_ADMIN_PRODUCTS_SEARCH_MAX_LENGTH = PRODUCT_NAME_MAX_LENGTH;