export const PRODUCT_TITLE_MIN_LENGTH = 5;
export const PRODUCT_TITLE_MAX_LENGTH = 60;
export const PRODUCT_DESCRIPTION_MIN_LENGTH = 20;
export const PRODUCT_DESCRIPTION_MAX_LENGTH = 150;

export const GET_ALL_ADMIN_PRODUCTS_MAX_LIMIT = 100;
export const GET_ALL_ADMIN_PRODUCTS_DEFAULT_LIMIT = 30;
export const GET_ALL_ADMIN_PRODUCTS_SEARCH_MAX_LENGTH =
	PRODUCT_DESCRIPTION_MAX_LENGTH;
export const GET_ALL_ADMIN_PRODUCTS_TAGS_MAX_LENGTH = 100;